services:
  stock-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - FLASK_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - CORS_ORIGIN=http://localhost
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped