[build]
builder = "nixpacks"
buildCommand = "echo 'Building both services...'"

[deploy]
startCommand = "echo 'Starting services...'"
healthcheckTimeout = 180
restartPolicy = "on-failure"

[[services]]
name = "backend"
directory = "stock-scanner-backend"  # Updated to correct backend directory
startCommand = "gunicorn -c gunicorn.conf.py app:app"  # Updated to use gunicorn config
healthcheckPath = "/api/stocks/current"
healthcheckTimeout = 180
buildCommand = "pip install -r requirements.txt"  # Added pip install command
envs = [
    "MONGODB_URI",
    "FLASK_ENV",
    "CORS_ORIGIN"
]

[[services]]
name = "frontend"
directory = "stock-scanner-frontend"
startCommand = "npm run start"
healthcheckPath = "/api/health"
buildCommand = "npm install && npm run build"
healthcheckTimeout = 180
envs = [
    "NEXT_PUBLIC_API_URL"
]