[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -c gunicorn.conf.py app:app"
restartPolicy = "on-failure"
healthcheckPath = "/health"
healthcheckTimeout = 180

[vars]
FLASK_ENV = "production" 