name: Weekly Stock Fetch

on:
  schedule:
    - cron: '30 11 * * 5'  
  workflow_dispatch:  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Streamlit App
        run: |
          curl -X GET "https://your-streamlit-app-url/?run_task=true"
