[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicy = "on-failure"
healthcheckPath = "/api/health"
healthcheckTimeout = 180